---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: depends-on-fail
  namespace: flux-system
spec:
  dependsOn:
  - name: podinfo-deploy-2-bad-kustomization
  interval: 1m0s
  path: ./
  prune: false
  sourceRef:
    kind: GitRepository
    name: podinfo-deploy