---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo-deploy
  namespace: flux-system
spec:
  interval: 2m0s
  ref:
    branch: main
  url: https://github.com/sympatheticmoose/podinfo-deploy

